from sqlalchemy import MetaData
from sqlalchemy.orm import DeclarativeBase

# Deterministic constraint/index names so every Alembic-generated migration
# is stable and reviewable instead of relying on each database backend's
# autogenerated (and non-deterministic) default names.
NAMING_CONVENTION = {
    "ix": "ix_%(column_0_label)s",
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    """Single shared declarative base for all persistent models.

    Every model in ``core.models`` must inherit from this class. Do not
    create additional ``Base`` classes elsewhere in the codebase.
    """

    metadata = MetaData(naming_convention=NAMING_CONVENTION)
