"""Stable, machine-readable error codes.

Route handlers must reference these constants rather than hardcoding error
code strings.
"""

VALIDATION_ERROR = "VALIDATION_ERROR"
UNAUTHORIZED = "UNAUTHORIZED"
FORBIDDEN = "FORBIDDEN"
NOT_FOUND = "NOT_FOUND"
CONFLICT = "CONFLICT"
BUSINESS_RULE_ERROR = "BUSINESS_RULE_ERROR"
INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"

# Authentication (Phase 2)
AUTH_INVALID_CREDENTIALS = "AUTH_INVALID_CREDENTIALS"
AUTH_TOKEN_INVALID = "AUTH_TOKEN_INVALID"
AUTH_TOKEN_EXPIRED = "AUTH_TOKEN_EXPIRED"
AUTH_REFRESH_TOKEN_REQUIRED = "AUTH_REFRESH_TOKEN_REQUIRED"
AUTH_USER_INACTIVE = "AUTH_USER_INACTIVE"
AUTH_EMAIL_ALREADY_EXISTS = "AUTH_EMAIL_ALREADY_EXISTS"
AUTH_PHONE_ALREADY_EXISTS = "AUTH_PHONE_ALREADY_EXISTS"

# Users / profiles / addresses / service areas (Phase 4)
CUSTOMER_PROFILE_ALREADY_EXISTS = "CUSTOMER_PROFILE_ALREADY_EXISTS"
PARTNER_PROFILE_ALREADY_EXISTS = "PARTNER_PROFILE_ALREADY_EXISTS"
SERVICE_AREA_NAME_ALREADY_EXISTS = "SERVICE_AREA_NAME_ALREADY_EXISTS"

# Role management
ROLE_ALREADY_ASSIGNED = "ROLE_ALREADY_ASSIGNED"
ROLE_NOT_ASSIGNED = "ROLE_NOT_ASSIGNED"
CANNOT_REMOVE_OWN_ADMIN_ROLE = "CANNOT_REMOVE_OWN_ADMIN_ROLE"

# Catalog (Phase 5)
SERVICE_NAME_ALREADY_EXISTS = "SERVICE_NAME_ALREADY_EXISTS"
MATERIAL_NAME_ALREADY_EXISTS = "MATERIAL_NAME_ALREADY_EXISTS"
SERVICE_MATERIAL_ALREADY_EXISTS = "SERVICE_MATERIAL_ALREADY_EXISTS"
PARTNER_CAPABILITY_ALREADY_EXISTS = "PARTNER_CAPABILITY_ALREADY_EXISTS"

# Pricing (Phase 6)
NO_ACTIVE_PRICING_RULE = "NO_ACTIVE_PRICING_RULE"
QUANTITY_REQUIRED = "QUANTITY_REQUIRED"
WEIGHT_REQUIRED = "WEIGHT_REQUIRED"
UNKNOWN_PRICING_MODEL = "UNKNOWN_PRICING_MODEL"

# Availability / slots / capacity (Phase 7)
SLOT_CAPACITY_EXCEEDED = "SLOT_CAPACITY_EXCEEDED"
RESERVATION_NOT_ACTIVE = "RESERVATION_NOT_ACTIVE"
